require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/survey_projects", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SurveyProject. As you add validations to SurveyProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SurveyProject.create! valid_attributes
      get survey_projects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      survey_project = SurveyProject.create! valid_attributes
      get survey_project_url(survey_project)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_survey_project_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      survey_project = SurveyProject.create! valid_attributes
      get edit_survey_project_url(survey_project)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SurveyProject" do
        expect {
          post survey_projects_url, params: { survey_project: valid_attributes }
        }.to change(SurveyProject, :count).by(1)
      end

      it "redirects to the created survey_project" do
        post survey_projects_url, params: { survey_project: valid_attributes }
        expect(response).to redirect_to(survey_project_url(SurveyProject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SurveyProject" do
        expect {
          post survey_projects_url, params: { survey_project: invalid_attributes }
        }.to change(SurveyProject, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post survey_projects_url, params: { survey_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested survey_project" do
        survey_project = SurveyProject.create! valid_attributes
        patch survey_project_url(survey_project), params: { survey_project: new_attributes }
        survey_project.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the survey_project" do
        survey_project = SurveyProject.create! valid_attributes
        patch survey_project_url(survey_project), params: { survey_project: new_attributes }
        survey_project.reload
        expect(response).to redirect_to(survey_project_url(survey_project))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        survey_project = SurveyProject.create! valid_attributes
        patch survey_project_url(survey_project), params: { survey_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested survey_project" do
      survey_project = SurveyProject.create! valid_attributes
      expect {
        delete survey_project_url(survey_project)
      }.to change(SurveyProject, :count).by(-1)
    end

    it "redirects to the survey_projects list" do
      survey_project = SurveyProject.create! valid_attributes
      delete survey_project_url(survey_project)
      expect(response).to redirect_to(survey_projects_url)
    end
  end
end
